### ISSUE TITLE
wow_messages refactor todo list

### ISSUE THREAD

**Issue by Victov** [Victov/wrath-rs#21]
This issue exists to keep track of the remaining work to refactor the server to use [wow_messages](https://github.com/gtker/wow_messages).

Some features are so half-implemented that it's better to remove them altogether and circle back to them later and do it properly. This is to avoid having to figure out how e.g. spells/talents work before being able to call this refactor completed, because then it would become a never-ending nightmare. 

- [x] Fix issue in wow_messages where SMSG_ADDON_INFO is serialized incorrectly.
- [x] Update readme pointing to wow_messages
- [x] Bump auth-server dependency wow_srp from 0.4 to 0.5
- [x] convert packets in `equipment_handler` to use wow_messages
- [x] convert packets in `instance_handler` to use wow_messages
- [x] Restore logout behaviour (`login_handler` and logout logic in `Character`)
- [x] Remove half-implemented Talents packets and cleanup related files
- [x] Remove half-implemented Spell packets and cleanup related files
- [x] convert packets in `queries_handler` to use wow_messages
- [x] restore all behaviour of `world_handler` (use wow_messages and hook up to relevant logic)
- [x] restore equipment in the character selection screen
- [x] Remove half-finished equipment related code (outside of character selection screen)
- [x] POSTPONED ~~Write converter for movement flags in update_builder~~ (see this [TODO](https://github.com/Victov/wrath-rs/blob/de7e4b82351c989cf78967803672ce2dfbc5a773/world_server/src/world/update_builder.rs#L23))
- [x] Do a pass of cleaning up stuff in `constants` that is no longer used. (or move to relevant enum in wow_messages)
- [x] remove `opcodes.rs`
- [x] Investigate if the entire depenency on `podio` can be deleted
- [x] POSTPONED ~~Create helper trait `UpdateMaskExt` for setting common flags/values on UpdateMask that have side-effects and refactor stuff out of `impl Character`~~
- [x] Verify that you can: Log in, see other people logging/out, see people walk in/out of range.
